Toma puto

diff --git a/apps/storefront/Dockerfile b/apps/storefront/Dockerfile
--- a/apps/storefront/Dockerfile
+++ b/apps/storefront/Dockerfile
@@ -1,61 +1,68 @@
-# syntax=docker/dockerfile:1.7
 
+# Stage 1: Base
 FROM node:20-alpine AS base
 
-ENV PNPM_HOME=/pnpm
-ENV PATH=$PNPM_HOME:$PATH
-
-RUN corepack enable && corepack prepare pnpm@9.0.0 --activate
-
+# Stage 2: Dependencies
 FROM base AS deps
-
 RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-COPY package.json pnpm-lock.yaml* ./
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
-RUN --mount=type=cache,id=storefront-pnpm-store,target=/pnpm/store \
-    pnpm fetch --frozen-lockfile
-
-RUN --mount=type=cache,id=storefront-pnpm-store,target=/pnpm/store \
-    pnpm install --frozen-lockfile --offline
-
+# Stage 3: Builder
 FROM base AS builder
-
 WORKDIR /app
 ARG NEXT_PUBLIC_VENDURE_API_URL
 ARG NEXT_PUBLIC_SITE_URL
-ARG NEXT_PUBLIC_ANDREANI_ENABLED
+ARG NEXT_PUBLIC_REQUIRE_CUSTOMER_VERIFICATION
 ENV NEXT_PUBLIC_VENDURE_API_URL=$NEXT_PUBLIC_VENDURE_API_URL
 ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
-ENV NEXT_PUBLIC_ANDREANI_ENABLED=$NEXT_PUBLIC_ANDREANI_ENABLED
-ENV NEXT_TELEMETRY_DISABLED=1
-
+ENV NEXT_PUBLIC_REQUIRE_CUSTOMER_VERIFICATION=$NEXT_PUBLIC_REQUIRE_CUSTOMER_VERIFICATION
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-RUN pnpm build
+# Environment variables for build time
+ENV NEXT_TELEMETRY_DISABLED=1
 
+RUN \
+    if [ -f yarn.lock ]; then yarn run build; \
+    elif [ -f package-lock.json ]; then npm run build; \
+    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
+# Stage 4: Runner
 FROM base AS runner
-
 WORKDIR /app
-
 RUN apk add --no-cache curl
 
 ENV NODE_ENV=production
 ENV NEXT_TELEMETRY_DISABLED=1
-ENV PORT=3000
-ENV HOSTNAME=0.0.0.0
 
-RUN addgroup --system --gid 1001 nodejs \
-    && adduser --system --uid 1001 nextjs
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 
+# Copy necessary files
 COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
 COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
 COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
 USER nextjs
 
 EXPOSE 3000
+
+ENV PORT=3000
+# set hostname to localhost
+ENV HOSTNAME="0.0.0.0"
 
 CMD ["node", "server.js"]
